#!/usr/bin/env bash
# Starts a GDB session on CSGO,
# Sets a couple of things up and then you can use GDB normally

function echo_red {
	echo -e "\e[31m$*\e[0m"
}

# breaks if you have steam_something=proton set
# because it finds that useless process instead of steam's shim
csgo_pid=$(pgrep -f "steam\.exe.*CheatersCheetah\.exe")
if [ -z "$csgo_pid" ]; then
    echo_red "CS:GO needs to be open..."
    exit 1
fi

#https://www.kernel.org/doc/Documentation/security/Yama.txt
echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temp until reboot.


echo "CSGO PID: " $csgo_pid
gdb_args=(
-ex "handle SIGUSR1 nostop noprint pass"
# steam expects to follow the child after attaching
-ex "set follow-fork-mode child"
-ex "continue"
# but don't follow forever because we'll end up in the unity crash handler.
# sometimes this breaks anyway and the game does nothing.
-ex "set follow-fork-mode parent"
-p $csgo_pid
)
sudo gdb "${gdb_args[@]}"
